import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>RSS Reader</title>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Stay updated with curated RSS feeds from timpepper.dev blog topics and beyond.
            Discover interesting content aligned with Tim Pepper's interests, studies, and work." />
        <link rel="stylesheet" type="text/css" href="css/feeds.css" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
